# Generated by Django 4.1.6 on 2023-04-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_balance_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(blank=True, default=53881),
        ),
    ]
