# Generated by Django 4.1.6 on 2023-04-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.IntegerField(blank=True, default=624670),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(blank=True, default=28796),
        ),
    ]
