# Generated by Django 4.1.6 on 2023-04-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
